M48
; DRILL file KiCad 10.0.1 date 2026-05-06T14:34:02
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-06T14:34:02-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X122.61Y-163.37
X128.39Y-163.37
T2
X95.2Y-168.1
T3
X84.0Y-74.0
X84.0Y-166.0
X136.0Y-74.0
X136.0Y-166.0
M30
